#!/system/bin/sh
# Tweaks for KSM
# http://review.cyanogenmod.org/#/c/12118/

echo 4000 > /sys/kernel/mm/ksm/sleep_millisecs;
echo 128 > /sys/kernel/mm/ksm/pages_to_scan;
echo 1 > /sys/kernel/mm/ksm/run;
